name: Generate Data Files

on:
  push:
    branches: [ main, master ]
    paths:
      - 'assets/**'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Generate data files
      run: |
        ruby _data/generate_data.rb

    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add _data/*.yml
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update data files from assets [skip ci]" && git push)